In [ ]:
!git clone --single-branch --branch pytorch_lab_structure https://YOUR_USER_NAME:YOUR_PW_OR_PAT@github.com/matthiaspfenninger/fsdl-active-learning.git # add your own username and pw/pat here

Cloning into 'new_directory'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.


In [ ]:
%cd fsdl-active-learning

In [ ]:
# alternative way: if you cloned the repository to your GDrive account, you can mount it here

#from google.colab import drive
#drive.mount('/content/drive', force_remount=True)
#%cd /content/drive/MyDrive/fsdl-active-learning

Mounted at /content/drive
/content/drive/MyDrive/fsdl-active-learning


In [ ]:
!pip3 install boltons wandb pytorch_lightning==1.1.4 pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 torchtext==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html # general lab / pytorch installs
!pip3 install modAL tensorflow # active learning project

%env PYTHONPATH=.:$PYTHONPATH

Looking in links: https://download.pytorch.org/whl/torch_stable.html
env: PYTHONPATH=.:$PYTHONPATH


In [ ]:
!python training/run_experiment.py --gpus=1 --max_epochs=1 --num_workers=4 --data_class=DroughtWatch --model_class=ResnetClassifier

2021-04-14 21:48:26.220601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Unzipping DroughtWatch file...
Loading train/validation datasets as TF tensor
2021-04-14 21:48:29.453041: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-14 21:48:29.453987: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-04-14 21:48:29.483623: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-14 21:48:29.484487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla K80 computeCapability: 3.7
coreClock: 0.8235GHz coreCount: 13 deviceMemorySize: 11.17GiB deviceMemoryBandwidth: 223.96GiB/s
20

In [ ]:
# peeking into preprocessed data can be done as following
import h5py
f = h5py.File("data/processed/droughtwatch/trainval.h5", "r")
print(f["x_train"][0:1])
print(f["y_train"][0:1])
print(f["x_val"])
print(f["y_val"])

[[[[ 35  32  34 ...   0 203 200]
   [ 33  30  32 ...   0 203 200]
   [ 33  30  32 ...   0 203 200]
   ...
   [ 34  30  30 ...   0 205 201]
   [ 33  29  27 ...   0 205 201]
   [ 33  28  27 ...   0 205 201]]

  [[ 32  28  30 ...   0 203 200]
   [ 32  30  32 ...   0 203 200]
   [ 33  30  32 ...   0 203 200]
   ...
   [ 34  30  31 ...   0 205 201]
   [ 34  30  29 ...   0 205 201]
   [ 33  29  27 ...   0 205 201]]

  [[ 31  28  28 ...   0 203 200]
   [ 32  29  29 ...   0 203 200]
   [ 32  29  31 ...   0 204 200]
   ...
   [ 34  30  29 ...   0 205 201]
   [ 34  30  30 ...   0 205 201]
   [ 34  30  30 ...   0 205 201]]

  ...

  [[ 37  33  33 ...   1 197 193]
   [ 38  35  35 ...   1 199 195]
   [ 32  28  28 ...   0 200 196]
   ...
   [ 47  44  46 ...   0 203 198]
   [ 38  35  39 ...   0 204 198]
   [ 34  30  33 ...   0 204 199]]

  [[ 46  44  44 ...   0 197 193]
   [ 39  36  38 ...   0 199 195]
   [ 35  32  36 ...   0 201 196]
   ...
   [ 44  42  44 ...   0 204 199]
   [ 35  32  35 ...   0 20